---
- hosts: all
  vars:
    home: /Users/lis2
    ruby: 2.0.0
    applications:
      - google-chrome
      - firefox
      - sublime-text
      - vlc
      - iterm2
      - sequel-pro
      - skype
      - dash
      - filezilla
      - picasa
      - viber
      - teamviewer
      - spotify
      - virtualbox
      - libreoffice
      - adium
      - subtitles
      - evernote
      - google-hangouts
      - alfred
      - appcleaner
    brew:
      - wget
      - apple-gcc42
      - git
      - ruby-build
      - mysql
      - tmux
      - mysql
      - macvim
      - nodejs
      - rbenv
      - zeromq
      - sqlite
      - scala
      - redis
      - htop-osx
      - irssi
      - the_silver_searcher
      - elixir
      - mongodb
      - docker
      
  tasks:  
    - name: Check for installed apps(casks)
      shell: brew list | grep {{ item }}
      register: installed_brews
      with_items: brew
      ignore_errors: true
 
    - name: Install apps with brew
      shell: brew install {{ item }}
      with_items: brew
      when: "{{ item not in installed_brews.results|map(attribute='stdout') }}"

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true
 
    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"
    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true
 
    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: applications
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    - name: Clone dotfiles
      git: repo=https://github.com/lis2/{{ item }}.git dest={{ home }}/{{ item }} force=no update=no
      with_items:
        - dotfiles       

    - name: Run symlink.rb
      shell: ruby {{ home }}/dotfiles/symlink.rb
    - name: install rvm
      shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

    - name: install ruby
      shell: ~/.rvm/bin/rvm install --default {{ ruby }} creates=~/.rvm/rubies/{{ ruby }}
